server:
  port: 8000
  servlet:
    context-path: /benefit-assetsearch-listener
spring:
  application:
    name: benefits-assets-search-listener
  profiles:
    active: dev
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: asset_search_indexing
  elasticsearch:
    host: vpc-membersearch-dev-pst2tchesygo64is3eg2gp3ehm.eu-west-1.es.amazonaws.com:80
    port: 80


fetch-asset-details-url: http://localhost:9000/benefit-asset-service/member-assets/{assetID}


visibilityscope:
  api:
    url: 'http://localhost:9002/api/benefits/v1/visibilityscope'
    readTimeOut: 4000
    connectionTimeOut: 4000
  validation:
    uris: '/benefits/data_asset/v1'
